"""
NEXUS OS — Core Builder (Meta-Plugin)
Autonomous plugin generation, AST validation, hot-swap loading, and auto-debugging.

This plugin lets NEXUS write its own Python plugins at runtime:
  1. LLM generates plugin code from a natural-language description
  2. AST sandbox validates syntax + scans for unsafe patterns
  3. Hot-swap loader writes, imports, and registers the plugin with the engine
  4. Auto-debugger catches errors, feeds traceback to LLM, patches, retries

Commands:
  • build_plugin  — generate + validate + hot-load a new plugin
  • list_generated — list all dynamically generated plugins
  • unload_plugin  — unload a generated plugin by name
  • reload_plugin  — reload (hot-swap) an existing generated plugin
  • heal_plugin    — auto-debug a broken generated plugin
"""

import ast
import importlib
import importlib.util
import json
import os
import re
import sys
import textwrap
import traceback
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

import httpx

from nexus.core.plugin import NexusPlugin
from nexus.core.logger import get_logger

log = get_logger("core_builder")

# ─── Safety Configuration ────────────────────────────────────────────────────

BLOCKED_IMPORTS = {
    # Direct dangerous modules
    "ctypes", "ctypes.wintypes",
    "winreg", "_winreg",
}

BLOCKED_FUNCTIONS = {
    # Functions that should not appear in generated code
    "os.system", "os.popen", "os.exec", "os.execl", "os.execle",
    "os.execlp", "os.execlpe", "os.execv", "os.execve", "os.execvp",
    "os.execvpe", "os.spawn", "os.spawnl", "os.spawnle",
    "subprocess.call", "subprocess.Popen",
    "shutil.rmtree", "shutil.move",
    "eval", "exec", "compile", "__import__",
    "globals", "locals", "getattr", "setattr", "delattr",
    "open",  # raw open — plugins should use pathlib or controlled helpers
}

# Regex patterns that indicate dangerous code
BLOCKED_PATTERNS = [
    r"subprocess\.(?:call|Popen|run)\(",  # subprocess invocation
    r"os\.(?:system|popen|exec|spawn)\(",  # os-level exec
    r"shutil\.rmtree\(",                   # recursive delete
    r"(?:^|\s)eval\s*\(",                  # eval call
    r"(?:^|\s)exec\s*\(",                  # exec call
    r"__import__\s*\(",                    # dynamic import
    r"ctypes\.",                           # C-level access
    r"winreg\.",                           # Windows registry
    r"socket\.(?:socket|connect|bind|listen)\(",  # raw sockets
]

# Network call patterns to detect for dynamic permission prompts
NETWORK_CALL_PATTERNS = [
    # httpx / requests / urllib
    r"httpx\.(?:get|post|put|patch|delete|head|options|Client|AsyncClient)\(",
    r"requests\.(?:get|post|put|patch|delete|head|options|Session)\(",
    r"urllib\.request\.(?:urlopen|Request)\(",
    # Playwright / browser navigation
    r"page\.goto\(",
    r"\.navigate\(",
]

# Allowed imports for generated plugins (whitelist approach)
SAFE_IMPORTS = {
    "os", "os.path", "sys", "re", "json", "math", "datetime", "time",
    "pathlib", "collections", "itertools", "functools", "typing",
    "hashlib", "base64", "uuid", "random", "string", "textwrap",
    "urllib.parse", "statistics", "dataclasses",
    "subprocess",  # allowed but subprocess.call/Popen blocked by pattern scan
    "shutil",      # allowed but shutil.rmtree blocked
    "requests", "httpx", "bs4", "PIL", "psutil",
    "nexus.core.plugin", "nexus.core.logger", "nexus.core.config",
}

# ─── Plugin Template ─────────────────────────────────────────────────────────

PLUGIN_TEMPLATE = '''"""
NEXUS OS — {title} (Auto-Generated Plugin)
{description}
Generated by core_builder.
"""

{imports}
from nexus.core.plugin import NexusPlugin


class {class_name}(NexusPlugin):
    name = "{plugin_name}"
    description = "{description}"
    version = "1.0.0"
    icon = "{icon}"

    def setup(self):
{setup_body}

{method_bodies}
'''

# ─── LLM Prompt ──────────────────────────────────────────────────────────────

CODE_GEN_PROMPT = """You are a Python code generator for NEXUS OS, a Windows desktop automation framework.

## Your Task
Generate a complete Python plugin based on the user's description.

## Plugin Architecture
Every plugin MUST:
1. Import `from nexus.core.plugin import NexusPlugin`
2. Subclass `NexusPlugin`
3. Set class attributes: `name`, `description`, `version`, `icon`
4. Override `setup()` to call `self.register_command(...)` for each command
5. Each command handler is a method: `def handler_name(self, **kwargs) -> dict`
6. Return `{{"success": True, "result": ...}}` on success
7. Return `{{"success": False, "error": "..."}}` on failure

## register_command Signature
```python
self.register_command(
    name="command_name",          # snake_case action name
    handler=self.method_ref,      # bound method
    description="What it does",   # human-readable
    usage="command_name <args>",  # usage example
    aliases=["alt_name"],         # optional aliases
    keywords=["key", "words"],    # for ML matching
)
```

## Safety Rules
- Do NOT use: eval, exec, __import__, os.system, os.popen, ctypes, winreg
- Do NOT use: subprocess.call, subprocess.Popen (use subprocess.run with capture_output=True)
- Do NOT use: shutil.rmtree (use pathlib unlink/rmdir for individual items)
- Do NOT use: raw `open()` — use `pathlib.Path.read_text()` / `write_text()` etc.
- All file operations MUST be scoped — no arbitrary path deletion
- Handle ALL exceptions gracefully in try/except blocks

## Output Format
Return ONLY a JSON object with NO markdown fences:
{{
    "plugin_name": "snake_case_name",
    "class_name": "PascalCaseName",
    "title": "Human Readable Title",
    "icon": "single_emoji",
    "description": "Brief description",
    "imports": ["import os", "from pathlib import Path"],
    "commands": [
        {{
            "name": "command_name",
            "method_name": "method_name",
            "description": "What it does",
            "usage": "command_name <args>",
            "aliases": [],
            "keywords": ["word1", "word2"],
            "params": ["param1", "param2"],
            "code": "def method_name(self, param1='', param2='', **kwargs):\\n    try:\\n        result = ...\\n        return {{\\"success\\": True, \\"result\\": result}}\\n    except Exception as e:\\n        return {{\\"success\\": False, \\"error\\": str(e)}}"
        }}
    ]
}}

## User Request
{description}
"""

HEAL_PROMPT = """You are a Python debugger for NEXUS OS plugins.

## The Problem
A generated plugin threw an error during execution.

## Error Traceback
```
{traceback}
```

## Current Plugin Source Code
```python
{source}
```

## Command That Failed
Action: {action}
Args: {args}

## Fix Instructions
1. Analyze the traceback and source code
2. Identify the root cause
3. Return the COMPLETE fixed source code for the entire plugin file

Return ONLY the fixed Python source code, no markdown fences, no explanation.
The code must be a complete, valid Python module that can replace the original file.
"""


class CoreBuilderPlugin(NexusPlugin):
    """Meta-plugin: generates, validates, loads, and heals other plugins."""

    name = "core_builder"
    description = "Autonomous plugin generator — NEXUS writes its own tools"
    version = "1.0.0"
    icon = "🏗️"

    # Directory for generated plugins
    GEN_DIR = Path(__file__).parent / "generated"
    GEN_PREFIX = "gen_"
    MAX_HEAL_ATTEMPTS = 3

    def setup(self):
        # Ensure generated plugins directory exists
        self.GEN_DIR.mkdir(parents=True, exist_ok=True)
        init_file = self.GEN_DIR / "__init__.py"
        if not init_file.exists():
            init_file.write_text('"""Auto-generated plugins directory."""\n')

        # Read LLM config
        self._llm_model = self.config.get("ai", "local_model") or "qwen2.5-coder:3b"
        self._llm_base = (self.config.get("ai", "local_base_url") or "http://127.0.0.1:11434").rstrip("/")

        # Track generated plugins  {name: file_path}
        self._generated: Dict[str, Path] = {}
        self._heal_counts: Dict[str, int] = {}

        # Discover previously generated plugins
        self._discover_existing()

        self.register_command(
            "build_plugin", self.build_plugin,
            "Generate a new plugin from a description",
            "build plugin <description>",
            aliases=["build", "create_plugin", "generate_plugin"],
            keywords=["build", "create", "generate", "plugin", "tool", "make", "write"],
        )
        self.register_command(
            "list_generated", self.list_generated,
            "List all dynamically generated plugins",
            "list generated plugins",
            aliases=["generated", "my_plugins"],
            keywords=["list", "generated", "plugins", "built", "created"],
        )
        self.register_command(
            "unload_generated", self.unload_generated,
            "Unload a generated plugin by name",
            "unload plugin <name>",
            aliases=["remove_plugin"],
            keywords=["unload", "remove", "delete", "plugin"],
        )
        self.register_command(
            "reload_generated", self.reload_generated,
            "Reload (hot-swap) a generated plugin",
            "reload plugin <name>",
            aliases=["hotswap"],
            keywords=["reload", "hotswap", "refresh", "plugin"],
        )
        self.register_command(
            "heal_plugin", self.heal_plugin,
            "Auto-debug and fix a broken generated plugin",
            "heal plugin <name>",
            aliases=["fix_plugin", "debug_plugin"],
            keywords=["heal", "fix", "debug", "repair", "plugin"],
        )
        self.register_command(
            "grant_permission", self._handle_grant_permission,
            "Grant network permission for a generated plugin",
            "grant permission <plugin_name> <mode>",
            aliases=["allow_domain", "permit_network"],
            keywords=["grant", "allow", "permit", "network", "domain", "permission"],
        )

        # In-memory store for pending permission requests
        self._pending_permissions: Dict[str, Dict] = {}
        self._onetime_grants: Dict[str, set] = {}

    # ─── Discovery ────────────────────────────────────────────────────────────

    def _discover_existing(self):
        """Scan GEN_DIR for previously generated plugins."""
        for py_file in self.GEN_DIR.glob(f"{self.GEN_PREFIX}*.py"):
            stem = py_file.stem  # e.g. gen_speed_test
            plugin_name = stem[len(self.GEN_PREFIX):]  # e.g. speed_test
            self._generated[plugin_name] = py_file
        if self._generated:
            log.info(f"Discovered {len(self._generated)} previously generated plugins: "
                     f"{', '.join(self._generated.keys())}")

    # ─── Engine Access ────────────────────────────────────────────────────────

    def _get_engine(self):
        """Get reference to the NexusEngine (set by engine after loading)."""
        # The engine sets itself on plugins after load_all_plugins
        return getattr(self, "_engine", None)

    # ─── LLM Interaction ─────────────────────────────────────────────────────

    def _call_llm(self, prompt: str, temperature: float = 0.1,
                  num_predict: int = 2000) -> str:
        """Call the local Ollama LLM and return raw text."""
        payload = {
            "model": self._llm_model,
            "prompt": prompt,
            "stream": False,
            "options": {
                "temperature": temperature,
                "num_predict": num_predict,
            },
        }
        with httpx.Client(timeout=120.0) as client:
            resp = client.post(f"{self._llm_base}/api/generate", json=payload)
        resp.raise_for_status()
        return (resp.json().get("response") or "").strip()

    def _parse_json_response(self, text: str) -> Optional[Dict]:
        """Extract JSON from LLM output, stripping markdown fences."""
        clean = text.strip()
        # Strip markdown fences
        if clean.startswith("```"):
            clean = re.sub(r"^```(?:json|python)?\s*", "", clean)
            clean = re.sub(r"\s*```\s*$", "", clean)

        try:
            return json.loads(clean)
        except json.JSONDecodeError:
            # Try to extract first JSON object/array
            m = re.search(r'(\{(?:[^{}]|\{(?:[^{}]|\{[^{}]*\})*\})*\})', clean, re.DOTALL)
            if m:
                try:
                    return json.loads(m.group(1))
                except json.JSONDecodeError:
                    pass
        return None

    # ─── AST Validation & Safety Scanner ─────────────────────────────────────

    def _validate_syntax(self, source: str) -> Tuple[bool, str]:
        """Parse source with ast.parse — returns (ok, error_msg)."""
        try:
            ast.parse(source)
            return True, ""
        except SyntaxError as e:
            return False, f"Syntax error at line {e.lineno}: {e.msg}"

    def _scan_safety(self, source: str) -> Tuple[bool, List[str]]:
        """
        Scan source code for unsafe patterns.
        Returns (is_safe, list_of_violations).
        """
        violations = []

        # ── Regex pattern scan ──
        for pattern in BLOCKED_PATTERNS:
            matches = re.findall(pattern, source, re.MULTILINE)
            if matches:
                violations.append(f"Blocked pattern: {pattern} (found {len(matches)}x)")

        # ── AST-based import scan ──
        try:
            tree = ast.parse(source)
        except SyntaxError:
            violations.append("Cannot AST-parse for safety scan (syntax errors)")
            return False, violations

        for node in ast.walk(tree):
            # Check import statements
            if isinstance(node, ast.Import):
                for alias in node.names:
                    if alias.name in BLOCKED_IMPORTS:
                        violations.append(f"Blocked import: {alias.name}")
            elif isinstance(node, ast.ImportFrom):
                module = node.module or ""
                if module in BLOCKED_IMPORTS:
                    violations.append(f"Blocked import: from {module}")
                # Check for from X import dangerous_func
                for alias in (node.names or []):
                    full = f"{module}.{alias.name}"
                    if full in BLOCKED_FUNCTIONS:
                        violations.append(f"Blocked function import: {full}")

            # Check for dangerous function calls
            elif isinstance(node, ast.Call):
                func_name = self._get_call_name(node)
                if func_name in BLOCKED_FUNCTIONS:
                    violations.append(f"Blocked function call: {func_name}()")

        return len(violations) == 0, violations

    def _get_call_name(self, node: ast.Call) -> str:
        """Extract the dotted name of a function call from AST."""
        if isinstance(node.func, ast.Name):
            return node.func.id
        elif isinstance(node.func, ast.Attribute):
            parts = []
            current = node.func
            while isinstance(current, ast.Attribute):
                parts.append(current.attr)
                current = current.value
            if isinstance(current, ast.Name):
                parts.append(current.id)
            return ".".join(reversed(parts))
        return ""

    def _validate_plugin_structure(self, source: str) -> Tuple[bool, str]:
        """Ensure the source contains a valid NexusPlugin subclass."""
        try:
            tree = ast.parse(source)
        except SyntaxError as e:
            return False, f"Syntax error: {e}"

        has_nexus_import = False
        has_plugin_class = False
        has_setup = False
        has_register = False

        for node in ast.walk(tree):
            # Check for NexusPlugin import
            if isinstance(node, ast.ImportFrom):
                if node.module and "nexus.core.plugin" in node.module:
                    for alias in (node.names or []):
                        if alias.name == "NexusPlugin":
                            has_nexus_import = True

            # Check for class that inherits NexusPlugin
            if isinstance(node, ast.ClassDef):
                for base in node.bases:
                    base_name = ""
                    if isinstance(base, ast.Name):
                        base_name = base.id
                    elif isinstance(base, ast.Attribute):
                        base_name = base.attr
                    if base_name == "NexusPlugin":
                        has_plugin_class = True
                        # Check for setup method
                        for item in node.body:
                            if isinstance(item, ast.FunctionDef) and item.name == "setup":
                                has_setup = True
                                # Check for register_command call inside setup
                                for sub in ast.walk(item):
                                    if isinstance(sub, ast.Call):
                                        call_name = self._get_call_name(sub)
                                        if "register_command" in call_name:
                                            has_register = True

        issues = []
        if not has_nexus_import:
            issues.append("Missing 'from nexus.core.plugin import NexusPlugin'")
        if not has_plugin_class:
            issues.append("No class inheriting from NexusPlugin found")
        if not has_setup:
            issues.append("Missing setup() method")
        if not has_register:
            issues.append("No register_command() calls found in setup()")

        if issues:
            return False, "; ".join(issues)
        return True, ""

    def _scan_network_urls(self, source: str) -> List[str]:
        """
        AST + regex scan for URLs referenced in network calls.
        Returns list of domains the generated code wants to contact.
        """
        from urllib.parse import urlparse
        domains = set()

        # 1. Regex scan for string literals that look like URLs
        url_pattern = re.compile(
            r'["\']+(https?://[^"\'\'\s]+)["\']',
            re.IGNORECASE,
        )
        for match in url_pattern.finditer(source):
            raw = match.group(1)
            try:
                host = urlparse(raw).hostname
                if host and host not in ("127.0.0.1", "localhost"):
                    domains.add(host.lower())
            except Exception:
                pass

        # 2. Detect network call patterns to confirm intent
        has_network_calls = False
        for pat in NETWORK_CALL_PATTERNS:
            if re.search(pat, source):
                has_network_calls = True
                break

        # Only return domains if the code actually makes network calls
        if not has_network_calls:
            return []

        return sorted(domains)

    def _get_allowed_domains(self) -> List[str]:
        """Read the current domain allowlist from config."""
        raw = self.config.get("safety", "web", "allowlist_domains")
        if isinstance(raw, list):
            return [str(d).lower().strip() for d in raw if str(d).strip()]
        return ["localhost", "github.com", "codeforces.com"]

    def _is_domain_allowed(self, domain: str) -> bool:
        """Check a domain against the allowlist (supports subdomain matching)."""
        domain = domain.lower().strip()
        for allowed in self._get_allowed_domains():
            if domain == allowed or domain.endswith(f".{allowed}"):
                return True
        return False

    def _add_domain_to_allowlist(self, domain: str):
        """Permanently add a domain to the YAML allowlist."""
        current = self._get_allowed_domains()
        domain = domain.lower().strip()
        if domain not in current:
            current.append(domain)
            self.config.set("safety", "web", "allowlist_domains", current)
            self.config.save()
            log.info(f"🔓 Domain '{domain}' added to permanent allowlist")

    def _check_network_permissions(self, plugin_name: str, source: str) -> Tuple[bool, str, List[str]]:
        """
        Scan generated code for network URLs. If any target non-allowlisted
        domains, return a permission request instead of blocking outright.

        Returns (clear_to_load, message, blocked_domains)
          - clear_to_load=True  → no new domains, or all domains are allowed
          - clear_to_load=False → needs user permission for blocked_domains
        """
        detected = self._scan_network_urls(source)
        if not detected:
            return True, "", []

        blocked = [d for d in detected if not self._is_domain_allowed(d)]
        if not blocked:
            return True, "", []

        msg = (
            f"[SECURITY] Generated plugin '{plugin_name}' is requesting "
            f"network access to: {', '.join(blocked)}"
        )
        log.warning(msg)
        return False, msg, blocked

    def grant_network_permission(self, plugin_name: str, domains: List[str],
                                  mode: str = "once") -> Dict[str, Any]:
        """
        Grant network permission for a pending plugin load.
        mode: 'once' = allow this load only, 'always' = add to YAML allowlist
        """
        # Resolve filepath from pending permissions OR from already-generated registry
        pending_info = self._pending_permissions.get(plugin_name, {})
        filepath_str = pending_info.get("filepath", "")
        filepath = Path(filepath_str) if filepath_str else self._generated.get(plugin_name)

        if mode == "always":
            for d in domains:
                self._add_domain_to_allowlist(d)
            log.info(f"🔓 Permanent access granted for: {', '.join(domains)}")
        elif mode == "once":
            self._onetime_grants[plugin_name] = set(domains)
            log.info(f"🔑 One-time access granted for '{plugin_name}': {', '.join(domains)}")
        elif mode == "block":
            # Delete the generated file and clean up
            if filepath and filepath.exists():
                filepath.unlink()
                log.info(f"🗑️ Blocked plugin '{plugin_name}' deleted: {filepath}")
            self._generated.pop(plugin_name, None)
            self._pending_permissions.pop(plugin_name, None)
            return {
                "success": True,
                "result": f"Plugin '{plugin_name}' blocked and deleted. No network access granted.",
            }

        # Now attempt the hot-load that was paused
        if not filepath or not filepath.exists():
            return {"success": False, "error": f"No pending file found for '{plugin_name}'"}

        ok, err = self._hot_load(plugin_name, filepath)
        if not ok:
            return {"success": False, "error": f"Permission granted but load failed: {err}"}

        # Clean up
        self._pending_permissions.pop(plugin_name, None)
        if mode == "once":
            self._onetime_grants.pop(plugin_name, None)

        engine = self._get_engine()
        plugin = engine.plugins.get(plugin_name) if engine else None
        cmd_count = len(plugin.get_commands()) if plugin else 0

        return {
            "success": True,
            "result": (
                f"🔓 Network access {'permanently allowed' if mode == 'always' else 'allowed once'} "
                f"for: {', '.join(domains)}\n"
                f"🔥 Plugin '{plugin_name}' loaded! ({cmd_count} commands)"
            ),
            "plugin_name": plugin_name,
            "domains_granted": domains,
            "permission_mode": mode,
        }

    def _full_validate(self, source: str) -> Tuple[bool, str]:
        """Run all validation passes. Returns (ok, combined_error)."""
        # 1. Syntax
        ok, err = self._validate_syntax(source)
        if not ok:
            return False, f"[SYNTAX] {err}"

        # 2. Safety
        safe, violations = self._scan_safety(source)
        if not safe:
            return False, f"[SAFETY] {'; '.join(violations)}"

        # 3. Structure
        ok, err = self._validate_plugin_structure(source)
        if not ok:
            return False, f"[STRUCTURE] {err}"

        return True, ""

    # ─── Code Assembly ────────────────────────────────────────────────────────

    def _assemble_plugin(self, spec: Dict) -> str:
        """Assemble a plugin .py file from the LLM JSON spec."""
        plugin_name = spec.get("plugin_name", "unnamed")
        class_name = spec.get("class_name", "GeneratedPlugin")
        title = spec.get("title", plugin_name)
        icon = spec.get("icon", "🔧")
        description = spec.get("description", "Auto-generated plugin")
        imports_list = spec.get("imports", [])
        commands = spec.get("commands", [])

        # Build imports block
        imports_block = "\n".join(imports_list) if imports_list else "import os\nfrom pathlib import Path"

        # Build setup body
        setup_lines = []
        for cmd in commands:
            name = cmd.get("name", "unknown")
            method = cmd.get("method_name", name)
            desc = cmd.get("description", "")
            usage = cmd.get("usage", name)
            aliases = cmd.get("aliases", [])
            keywords = cmd.get("keywords", [])
            setup_lines.append(
                f'        self.register_command(\n'
                f'            "{name}", self.{method},\n'
                f'            "{desc}",\n'
                f'            "{usage}",\n'
                f'            aliases={aliases!r},\n'
                f'            keywords={keywords!r},\n'
                f'        )'
            )
        setup_body = "\n".join(setup_lines) if setup_lines else "        pass"

        # Build method bodies
        method_blocks = []
        for cmd in commands:
            code = cmd.get("code", "")
            if code:
                # Ensure proper indentation (4 spaces for class method)
                dedented = textwrap.dedent(code)
                indented = textwrap.indent(dedented, "    ")
                method_blocks.append(indented)
            else:
                method = cmd.get("method_name", cmd.get("name", "unknown"))
                params = cmd.get("params", [])
                param_str = ", ".join(f"{p}=''" for p in params)
                if param_str:
                    param_str = ", " + param_str
                method_blocks.append(
                    f"    def {method}(self{param_str}, **kwargs):\n"
                    f"        return {{\"success\": True, \"result\": \"Not implemented yet\"}}"
                )

        method_body = "\n\n".join(method_blocks) if method_blocks else (
            "    def _placeholder(self):\n        pass"
        )

        source = PLUGIN_TEMPLATE.format(
            title=title,
            description=description,
            imports=imports_block,
            class_name=class_name,
            plugin_name=plugin_name,
            icon=icon,
            setup_body=setup_body,
            method_bodies=method_body,
        )

        return source

    # ─── Hot-Swap Loader ─────────────────────────────────────────────────────

    def _write_plugin_file(self, plugin_name: str, source: str) -> Path:
        """Write validated source to nexus/plugins/generated/gen_<name>.py."""
        filename = f"{self.GEN_PREFIX}{plugin_name}.py"
        filepath = self.GEN_DIR / filename
        filepath.write_text(source, encoding="utf-8")
        log.info(f"Wrote generated plugin: {filepath}")
        return filepath

    def _hot_load(self, plugin_name: str, filepath: Path) -> Tuple[bool, str]:
        """Import and register the plugin dynamically with the engine."""
        engine = self._get_engine()
        if not engine:
            return False, "No engine reference — cannot register plugin"

        # Build module name relative to nexus package
        module_name = f"nexus.plugins.generated.{self.GEN_PREFIX}{plugin_name}"

        try:
            # If already loaded, unload first
            if plugin_name in engine.plugins:
                engine.unload_plugin(plugin_name)

            # Remove from sys.modules for clean reload
            if module_name in sys.modules:
                del sys.modules[module_name]

            # Dynamic import
            spec = importlib.util.spec_from_file_location(module_name, filepath)
            if spec is None or spec.loader is None:
                return False, f"Could not create import spec for {filepath}"

            module = importlib.util.module_from_spec(spec)
            sys.modules[module_name] = module
            spec.loader.exec_module(module)

            # Find the NexusPlugin subclass in the module
            plugin_class = None
            for attr_name in dir(module):
                attr = getattr(module, attr_name)
                if (isinstance(attr, type)
                        and issubclass(attr, NexusPlugin)
                        and attr is not NexusPlugin):
                    plugin_class = attr
                    break

            if not plugin_class:
                return False, "No NexusPlugin subclass found in generated module"

            # Instantiate and register
            plugin_instance = plugin_class()
            engine.load_plugin(plugin_instance)

            # Give the generated plugin an engine reference too
            plugin_instance._engine = engine

            # Update LLM command list
            engine.gemini.update_commands(engine.get_all_commands())

            self._generated[plugin_name] = filepath
            log.info(f"🔥 Hot-loaded plugin: {plugin_name} "
                     f"({len(plugin_instance.get_commands())} commands)")

            return True, ""

        except Exception as e:
            tb = traceback.format_exc()
            log.error(f"Hot-load failed for {plugin_name}: {e}\n{tb}")
            return False, f"Import/register error: {e}"

    # ─── Auto-Debugger ───────────────────────────────────────────────────────

    def _auto_heal(self, plugin_name: str, error_trace: str,
                   action: str = "", args: Dict = None) -> Tuple[bool, str, str]:
        """
        Feed error + source to LLM, get patched code, validate, hot-swap.
        Returns (success, message, new_source).
        """
        filepath = self._generated.get(plugin_name)
        if not filepath or not filepath.exists():
            return False, f"No source file found for plugin '{plugin_name}'", ""

        source = filepath.read_text(encoding="utf-8")
        heal_count = self._heal_counts.get(plugin_name, 0)

        if heal_count >= self.MAX_HEAL_ATTEMPTS:
            return False, (f"Max heal attempts ({self.MAX_HEAL_ATTEMPTS}) reached for "
                          f"'{plugin_name}'. Manual fix needed."), source

        prompt = HEAL_PROMPT.format(
            traceback=error_trace,
            source=source,
            action=action or "unknown",
            args=json.dumps(args or {}, default=str),
        )

        try:
            patched = self._call_llm(prompt, temperature=0.05, num_predict=3000)

            # Strip markdown if present
            if patched.startswith("```"):
                patched = re.sub(r"^```(?:python)?\s*", "", patched)
                patched = re.sub(r"\s*```\s*$", "", patched)

            # Validate the patch
            ok, err = self._full_validate(patched)
            if not ok:
                self._heal_counts[plugin_name] = heal_count + 1
                return False, f"Healed code failed validation: {err}", patched

            # Write and hot-swap
            self._write_plugin_file(plugin_name, patched)
            ok, err = self._hot_load(plugin_name, filepath)
            if not ok:
                self._heal_counts[plugin_name] = heal_count + 1
                return False, f"Healed code failed to load: {err}", patched

            self._heal_counts[plugin_name] = 0  # Reset on success
            return True, f"Plugin '{plugin_name}' healed and reloaded!", patched

        except Exception as e:
            self._heal_counts[plugin_name] = heal_count + 1
            return False, f"Heal LLM call failed: {e}", ""

    # ─── Intercepted Execute with Auto-Heal ──────────────────────────────────

    def execute_with_heal(self, plugin_name: str, action: str,
                          args: Dict) -> Dict[str, Any]:
        """
        Execute a command on a generated plugin with auto-heal on failure.
        If execution raises, feed traceback to LLM → patch → retry.
        """
        engine = self._get_engine()
        if not engine:
            return {"success": False, "error": "No engine reference"}

        plugin = engine.plugins.get(plugin_name)
        if not plugin:
            return {"success": False, "error": f"Plugin '{plugin_name}' not loaded"}

        result = plugin.execute(action, args)

        if not result.get("success") and plugin_name in self._generated:
            error_msg = result.get("error", "Unknown error")
            log.warning(f"Generated plugin {plugin_name}.{action} failed: {error_msg}")

            # Attempt auto-heal
            ok, msg, _ = self._auto_heal(
                plugin_name,
                error_trace=error_msg,
                action=action,
                args=args,
            )
            if ok:
                # Retry the command on the healed plugin
                plugin = engine.plugins.get(plugin_name)
                if plugin:
                    result = plugin.execute(action, args)
                    result["auto_healed"] = True
                    result["heal_message"] = msg

        return result

    # ═══════════════════════════════════════════════════════════════════════════
    # ── Command Handlers ──────────────────────────────────────────────────────
    # ═══════════════════════════════════════════════════════════════════════════

    def build_plugin(self, description: str = "", query: str = "", **kwargs) -> Dict[str, Any]:
        """Generate a new plugin from a natural-language description."""
        desc = description or query
        if not desc:
            return {
                "success": False,
                "error": "Please provide a description of the plugin you want to build.\n"
                         "Example: build plugin that checks internet speed and latency",
            }

        log.info(f"🏗️ Building plugin: {desc}")

        # ── Step 1: Ask LLM to generate the spec ──
        try:
            prompt = CODE_GEN_PROMPT.format(description=desc)
            raw = self._call_llm(prompt, temperature=0.15, num_predict=3000)
        except Exception as e:
            return {"success": False, "error": f"LLM call failed: {e}"}

        spec = self._parse_json_response(raw)
        if not spec:
            return {
                "success": False,
                "error": "LLM returned invalid JSON. Try rephrasing your description.",
                "raw_output": raw[:500],
            }

        plugin_name = spec.get("plugin_name", "").strip()
        if not plugin_name:
            return {"success": False, "error": "LLM didn't provide a plugin_name", "spec": spec}

        # Sanitize name
        plugin_name = re.sub(r"[^a-z0-9_]", "_", plugin_name.lower()).strip("_")
        spec["plugin_name"] = plugin_name

        # ── Step 2: Assemble source code ──
        source = self._assemble_plugin(spec)

        # ── Step 3: Validate ──
        ok, err = self._full_validate(source)
        if not ok:
            # Try to get LLM to fix it (one attempt)
            log.warning(f"Generated code failed validation: {err}")
            fix_prompt = (
                f"The following Python plugin code has validation errors:\n"
                f"ERRORS: {err}\n\n"
                f"SOURCE:\n```python\n{source}\n```\n\n"
                f"Return the COMPLETE fixed Python source code. No markdown fences. "
                f"No explanation. Just the corrected Python code."
            )
            try:
                fixed = self._call_llm(fix_prompt, temperature=0.05, num_predict=3000)
                if fixed.startswith("```"):
                    fixed = re.sub(r"^```(?:python)?\s*", "", fixed)
                    fixed = re.sub(r"\s*```\s*$", "", fixed)
                ok2, err2 = self._full_validate(fixed)
                if ok2:
                    source = fixed
                    log.info("LLM self-corrected the validation errors")
                else:
                    return {
                        "success": False,
                        "error": f"Generated code failed validation even after self-correction.\n"
                                 f"Original: {err}\nAfter fix: {err2}",
                    }
            except Exception as fix_e:
                return {"success": False, "error": f"Validation failed ({err}), and fix attempt errored: {fix_e}"}

        # ── Step 4: Write file ──
        filepath = self._write_plugin_file(plugin_name, source)

        # ── Step 4.5: Network permission check ──
        clear, perm_msg, blocked_domains = self._check_network_permissions(plugin_name, source)
        if not clear:
            # Pause the load — push a permission prompt
            self._pending_permissions[plugin_name] = {
                "domains": blocked_domains,
                "filepath": str(filepath),
                "source": source,
                "spec": spec,
            }
            return {
                "success": True,
                "requires_permission": True,
                "result": (
                    f"🏗️ Plugin '{plugin_name}' generated and validated!\n\n"
                    f"⚠️  [SECURITY] This plugin wants network access to:\n"
                    f"   {', '.join(blocked_domains)}\n\n"
                    f"Choose an option:\n"
                    f"  [1] Allow Once  → grant permission {plugin_name} once\n"
                    f"  [2] Allow Always (add to config) → grant permission {plugin_name} always\n"
                    f"  [3] Block & Delete → grant permission {plugin_name} block"
                ),
                "plugin_name": plugin_name,
                "blocked_domains": blocked_domains,
                "commands": [
                    f"grant permission {plugin_name} once",
                    f"grant permission {plugin_name} always",
                    f"grant permission {plugin_name} block",
                ],
                "file": str(filepath),
            }

        # ── Step 5: Hot-load ──
        ok, err = self._hot_load(plugin_name, filepath)
        if not ok:
            return {
                "success": False,
                "error": f"Plugin generated but failed to load: {err}",
                "file": str(filepath),
            }

        # ── Success! ──
        engine = self._get_engine()
        plugin = engine.plugins.get(plugin_name) if engine else None
        cmd_count = len(plugin.get_commands()) if plugin else 0

        return {
            "success": True,
            "result": (
                f"🏗️ Plugin '{plugin_name}' built and loaded!\n"
                f"   📦 {cmd_count} commands registered\n"
                f"   📁 {filepath}\n"
                f"   🔥 Hot-loaded into NEXUS — ready to use!"
            ),
            "plugin_name": plugin_name,
            "commands": [c.get("name") for c in spec.get("commands", [])],
            "file": str(filepath),
        }

    def list_generated(self, **kwargs) -> Dict[str, Any]:
        """List all dynamically generated plugins."""
        if not self._generated:
            return {
                "success": True,
                "result": "No generated plugins yet. Use 'build plugin <description>' to create one!",
            }

        engine = self._get_engine()
        lines = ["🏗️ Generated Plugins:"]
        for name, path in self._generated.items():
            loaded = "✅ loaded" if (engine and name in engine.plugins) else "⚪ not loaded"
            lines.append(f"  • {name} — {loaded} ({path.name})")

        return {"success": True, "result": "\n".join(lines), "plugins": list(self._generated.keys())}

    def unload_generated(self, name: str = "", query: str = "", **kwargs) -> Dict[str, Any]:
        """Unload a generated plugin."""
        target = name or query
        if not target:
            return {"success": False, "error": "Specify the plugin name to unload"}

        target = target.strip().lower().replace(" ", "_")
        if target not in self._generated:
            return {"success": False, "error": f"'{target}' is not a generated plugin",
                    "available": list(self._generated.keys())}

        engine = self._get_engine()
        if engine and target in engine.plugins:
            engine.unload_plugin(target)
            engine.gemini.update_commands(engine.get_all_commands())

        return {"success": True, "result": f"Plugin '{target}' unloaded."}

    def reload_generated(self, name: str = "", query: str = "", **kwargs) -> Dict[str, Any]:
        """Reload (hot-swap) a generated plugin from disk."""
        target = name or query
        if not target:
            return {"success": False, "error": "Specify the plugin name to reload"}

        target = target.strip().lower().replace(" ", "_")
        filepath = self._generated.get(target)
        if not filepath or not filepath.exists():
            return {"success": False, "error": f"No generated file found for '{target}'",
                    "available": list(self._generated.keys())}

        ok, err = self._hot_load(target, filepath)
        if not ok:
            return {"success": False, "error": f"Reload failed: {err}"}

        return {"success": True, "result": f"🔥 Plugin '{target}' reloaded!"}

    def heal_plugin(self, name: str = "", query: str = "",
                    error: str = "", **kwargs) -> Dict[str, Any]:
        """Auto-debug and fix a broken generated plugin."""
        target = name or query
        if not target:
            return {"success": False, "error": "Specify the plugin name to heal"}

        target = target.strip().lower().replace(" ", "_")
        filepath = self._generated.get(target)
        if not filepath or not filepath.exists():
            return {"success": False, "error": f"No generated file found for '{target}'"}

        error_trace = error or "Plugin reported an error during execution (no specific traceback)"

        ok, msg, patched = self._auto_heal(
            target,
            error_trace=error_trace,
            action="manual_heal",
            args={},
        )

        if ok:
            return {"success": True, "result": f"🩺 {msg}"}
        else:
            return {"success": False, "error": f"Heal failed: {msg}"}

    # ─── Auto-Load Previously Generated Plugins ──────────────────────────────

    def _handle_grant_permission(self, name: str = "", query: str = "",
                                   mode: str = "once", **kwargs) -> Dict[str, Any]:
        """
        Handle the grant permission command from user.
        Usage: grant permission <plugin_name> <once|always|block>
        """
        target = name or query
        if not target:
            return {"success": False, "error": "Specify the plugin name and mode (once / always / block)"}

        # Parse "plugin_name mode" from a single string
        parts = target.strip().split()
        if len(parts) >= 2:
            target = parts[0]
            mode = parts[-1]
        target = target.strip().lower().replace(" ", "_")
        mode = mode.strip().lower()

        if mode not in ("once", "always", "block"):
            return {
                "success": False,
                "error": f"Invalid mode '{mode}'. Use: once, always, or block",
            }

        pending = self._pending_permissions.get(target)
        if not pending:
            return {
                "success": False,
                "error": f"No pending permission request for '{target}'",
                "available": list(self._pending_permissions.keys()),
            }

        domains = pending["domains"]

        # Don't pop yet — grant_network_permission needs the filepath from pending
        return self.grant_network_permission(target, domains, mode)

    def auto_load_all_generated(self):
        """Load all previously generated plugins (called by engine after startup)."""
        loaded = 0
        failed = 0
        deferred = 0
        for name, filepath in self._generated.items():
            if filepath.exists():
                try:
                    source = filepath.read_text(encoding="utf-8")
                    ok, err = self._full_validate(source)
                    if not ok:
                        log.warning(f"Skipping invalid generated plugin '{name}': {err}")
                        failed += 1
                        continue

                    # Check network permissions before auto-loading
                    clear, perm_msg, blocked_domains = self._check_network_permissions(name, source)
                    if not clear:
                        self._pending_permissions[name] = {
                            "domains": blocked_domains,
                            "filepath": str(filepath),
                            "source": source,
                        }
                        log.warning(
                            f"⚠️  [SECURITY] Plugin '{name}' deferred — needs permission "
                            f"for: {', '.join(blocked_domains)}. "
                            f"Run: grant permission {name} once/always/block"
                        )
                        deferred += 1
                        continue

                    success, load_err = self._hot_load(name, filepath)
                    if success:
                        loaded += 1
                    else:
                        log.warning(f"Failed to auto-load generated plugin '{name}': {load_err}")
                        failed += 1
                except Exception as e:
                    log.warning(f"Error auto-loading '{name}': {e}")
                    failed += 1

        if loaded or failed or deferred:
            log.info(f"🏗️ Auto-loaded {loaded} generated plugins ({failed} failed, {deferred} awaiting permission)")
